# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5345e7f4c5e5f37f60517703f9f829e6"
application_url = "https://securities-hack-library-sees.trycloudflare.com"
embedded = true
name = "text-flow"
handle = "text-flow"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "textflow-dev.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillments/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = [ "customers/delete" ]
  uri = "/webhooks/customers/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_customers, write_customers, read_fulfillments, write_fulfillments, write_products"

[auth]
redirect_urls = [
  "https://securities-hack-library-sees.trycloudflare.com/auth/callback",
  "https://securities-hack-library-sees.trycloudflare.com/auth/shopify/callback",
  "https://securities-hack-library-sees.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
