export const UI_STRINGS = {
  TITLE: "TextFlow - SMS Automations",
  HEADING: "Set up SMS automations to engage customers",
  SUBHEADING: "Automate messages for abandoned carts, promotions, reviews and more.",
  BUTTON_CREATE: "Create New Automation",
  MODAL_TITLE: "Create New SMS Automation",
  EDIT_AUTOMATION_TITLE: "Edit SMS Automation",  
  SELECT_EVENT: "Select Event",
  SMS_MESSAGE: "SMS Message",
  ENABLE_AUTOMATION: "Enable Automation",
  DELAY_MINUTES: "Delay Before Sending (minutes)",
  SAVE_AUTOMATION: "Save Automation",
  UPDATE_AUTOMATION: "Update Automation", 
  CANCEL: "Cancel",
  SELECT_RECIPIENTS: "Select Recipients (To be fetched from Shopify API)",
};
